version: '2'

services:
  db55:
    container_name: magento2db55
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: magento
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3307:3306"
    volumes:
      - "./conf:/etc/mysql/conf.d"
      - db55-volume:/var/lib/mysql
volumes:
  db55-volume:
networks:
  default:
    external:
      name: env_default
