# https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docker.html#docker
FROM docker.elastic.co/elasticsearch/elasticsearch:7.16.3
COPY --chown=elasticsearch:elasticsearch config/elasticsearch.yml /usr/share/elasticsearch/config/
